---

- name: Install and Start NGINX of latest version
  become: yes
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Configure NGINX for sample.com
  become: yes
  template:
    src: nginx-template.j2
    dest: /etc/nginx/sites-available/sample.com
    owner: root
    mode: u=rw,g=r,o=r  

- name: Creating a simlink
  become: yes
  file: 
    src: /etc/nginx/sites-available/sample.com
    dest: /etc/nginx/sites-enabled/sample.com
    state: link
    owner: root
  notify: reload NGINX


