---

- name: Add PPA
  become: yes
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present
  tags:
    - php

- name: install PHP packages
  become: yes
  apt:
  with_items:
    - git
    - tar
    - unzip
    - php{{php_version}}-cli
    - php{{php_version}}-opcache
    - php{{php_version}}-json
    - php{{php_version}}-mbstring
    - php{{php_version}}-xml
    - php{{php_version}}-gd
    - php{{php_version}}-curl
  tags:
    - pp
    - php

- name: install php-mysql
  apt:
    name: php{{php_version}}-mysql
    state: present
  tags:
    - php

- name: install php-fpm
  become: yes
  apt:
    name: php{{php_version}}-fpm
    state: present 
  notify: restart php-fpm
  tags:
    - php